
spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: oracle
        password: 1
        driverClassName: oracle.jdbc.OracleDriver
    jpa:
        hibernate:            
            show-sql: true
            ddl-auto: update
